services:
  - type: web
    name: plant-monitoring-app
    env: node
    plan: free
    buildCommand: ./deploy-render.sh
    startCommand: ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: plant-monitoring-db
          property: connectionString
    healthCheckPath: /api/plants

databases:
  - name: plant-monitoring-db
    databaseName: plant_monitoring
    user: plant_user
    plan: free