services:
  - type: web
    name: plant-monitoring-app
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run db:push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: plant-monitoring-db
          property: connectionString
    healthCheckPath: /api/plants

databases:
  - name: plant-monitoring-db
    databaseName: plant_monitoring
    user: plant_user
    plan: free